spring:
  application:
    name: team
  datasource:
    url: jdbc:postgresql://localhost:5432/pm_team?currentSchema=development
    username: pm_team
    password: pm_team
  liquibase:
    change-log: classpath:db/liquibase/master.yaml

server:
  port: 8082

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true

