spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: team
          uri: lb://TEAM
          predicates:
            - Path=/team/**
          filters:
            - PrefixPath=/api
        - id: player
          uri: lb://PLAYER
          predicates:
            - Path=/player/**
          filters:
            - PrefixPath=/api
        - id: transfer
          uri: lb://TRANSFER
          predicates:
            - Path=/transfer/**
          filters:
            - PrefixPath=/api

server:
  port: 8989

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true