spring:
  application:
    name: transfer
  datasource:
    url: jdbc:postgresql://localhost:5432/pm_transfer?currentSchema=development
    username: pm_transfer
    password: pm_transfer

server:
  port: 8081

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true